# Generated by Django 3.0.2 on 2020-11-11 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'GitHubUser',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=60, unique=True)),
                ('associated_number', models.IntegerField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='RepoTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponame', models.CharField(max_length=100, unique=True)),
                ('repotype1', models.IntegerField(max_length=3)),
                ('repotype2', models.IntegerField(max_length=3)),
                ('repotype3', models.IntegerField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'RepoTypes',
            },
        ),
        migrations.CreateModel(
            name='Users_Repos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_repo', to='recommender.RepoTypes')),
            ],
            options={
                'verbose_name_plural': 'User_Repos',
            },
        ),
        migrations.CreateModel(
            name='User_Repo_Type_Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('contribution_count', models.IntegerField(max_length=3)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RepoType', to='recommender.Languages')),
            ],
            options={
                'verbose_name_plural': 'User_Repo_Type_Contribution_Count',
            },
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='recommender.GithubUsers')),
                ('githubuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerned_person', to='recommender.GithubUsers')),
            ],
            options={
                'verbose_name_plural': 'Following',
            },
        ),
    ]
