# Generated by Django 3.0.2 on 2020-11-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repotypes',
            name='repotype1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='repotypes',
            name='repotype2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='repotypes',
            name='repotype3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_repo_type_contribution',
            name='contribution_count',
            field=models.IntegerField(),
        ),
    ]
