# Generated by Django 3.0.2 on 2020-11-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20201111_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='associated_number',
            field=models.IntegerField(unique=True),
        ),
    ]
