# Generated by Django 3.0.2 on 2020-11-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20201111_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='followee',
            field=models.CharField(max_length=60),
        ),
    ]
