# Generated by Django 3.0.2 on 2020-11-21 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_auto_20201111_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommendedrepossimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('reponame', models.CharField(max_length=100)),
                ('similaruser', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ReposBasedonSimilarity',
            },
        ),
        migrations.CreateModel(
            name='recommendedreposfollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('reponame', models.CharField(max_length=100)),
                ('similaruser', models.CharField(max_length=100)),
                ('repotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repotype', to='recommender.Languages')),
            ],
            options={
                'verbose_name_plural': 'ReposBasedonFollowing',
            },
        ),
    ]
