# Generated by Django 3.0.2 on 2020-11-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_auto_20201121_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommendedRepositories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('reponame', models.CharField(max_length=100)),
                ('similaruser', models.CharField(max_length=100)),
                ('repotype', models.CharField(default='-', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'ReposRecommended',
            },
        ),
        migrations.DeleteModel(
            name='recommendedrepossimilarity',
        ),
    ]
