# Generated by Django 3.0.2 on 2020-11-21 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_auto_20201121_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommendedReposSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('reponame', models.CharField(max_length=100)),
                ('similaruser', models.CharField(max_length=100)),
                ('repotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repolang', to='recommender.Languages')),
            ],
            options={
                'verbose_name_plural': 'ReposRecommendedSimilarity',
            },
        ),
        migrations.DeleteModel(
            name='recommendedRepositories',
        ),
    ]
